### ISSUE TITLE
Is this German only?

### ISSUE THREAD

**Issue by kylebakerio** [Kovah/Taboo-Data#5]
I don't see English anywhere, but confused since the readme is in English and German just looks like a module with default categories in English?

**Comment by Kovah** [comment]
Yes, the coding base and readme are in english, but the first dataset is in german only. I am native German and it was easier to create a broad range of words across categories. The most recent pull request adds multi language support so adding new languages should be possible.

**Comment by kylebakerio** [comment]
That's unfortunate. Might want to note available languages directly in readme, I only checked to be safe because I noticed the example there was German.

How were the German sets developed? Did you make them yourself by hand? Do you happen to know of any English datasets anywhere?

**Comment by Kovah** [comment]
Sorry for this misunderstanding. Will make this clear in the Readme.

German set was developed by hand based on some inspiration from the board game. I do not know English datasets, so translating would have been my way to go.

**Comment by kylebakerio** [comment]
Thanks for the quick responses. It's a very cool project--wish it had english! A thought that comes to mind is generating word-sets from a thesaurus, and then looking over them by hand to add cultural references and remove unnecessary automatic entries. Just need a thesaurus to scrape from, and maybe an original collection of words to look up (could be category lists of animals, etc., like you've done--though animals wouldn't be best in a thesaurus).

Cheers.

**Comment by Kovah** [comment]
Sure. I bet there's an easy way to get an english word set for the next version.

**Comment by Kovah** [comment]
Version 2 with an English dataset was just released.
